### ISSUE TITLE
Viz media want update

### ISSUE THREAD

**Issue by shedman214** [Snd-R/komf#184]
is something wrong with viz media. when i manually select it. https://dpaste.org/qCN0S

**Comment by papaj-na-wrotkach** [comment]
I have the same issue with another manga. It seems like the url is wrong.
In your case komf tries to access
[`https://www.viz.com/read/manga/manga-books/manga/rosariovampire-season-ii-volume-1/product/2214/paperback`](https://www.viz.com/read/manga/manga-books/manga/rosariovampire-season-ii-volume-1/product/2214/paperback), but it should be
[`https://www.viz.com/manga-books/manga/rosariovampire-season-ii-volume-1/product/2214/digital`](https://www.viz.com/manga-books/manga/rosariovampire-season-ii-volume-1/product/2214/digital) - without the initial `/read/manga` in the path and `digital` instead of `paperback` at the end.

Btw, it seems like they updated the url scheme. Old one still works. The only difference in the new scheme is changing `/read/manga` to `/manga-books/manga` - in this case it would be [`https://www.viz.com/read/manga/rosariovampire-season-ii-volume-1/product/2214/digital`](https://www.viz.com/read/manga/rosariovampire-season-ii-volume-1/product/2214/digital). The change might be the source of the issue - notice that the broken url contains both old and new path fragments.

**Comment by papaj-na-wrotkach** [comment]
I think the code needs changes around here:
https://github.com/Snd-R/komf/blob/b3326888c187b79d70555f7b29143f33c41774e3/komf-core/src/commonMain/kotlin/snd/komf/providers/viz/VizParser.kt#L44
also here
https://github.com/Snd-R/komf/blob/b3326888c187b79d70555f7b29143f33c41774e3/komf-core/src/commonMain/kotlin/snd/komf/providers/viz/VizParser.kt#L120
and here
https://github.com/Snd-R/komf/blob/b3326888c187b79d70555f7b29143f33c41774e3/komf-core/src/commonMain/kotlin/snd/komf/providers/viz/VizParser.kt#L142

these two do not need changes as the old scheme still works, but it could be changed to keep consistency:
https://github.com/Snd-R/komf/blob/f27c45fc8aad1ade7a67b55c5b0d0335e39a0372/komf-core/src/commonMain/kotlin/snd/komf/providers/viz/VizClient.kt#L34
https://github.com/Snd-R/komf/blob/f27c45fc8aad1ade7a67b55c5b0d0335e39a0372/komf-core/src/commonMain/kotlin/snd/komf/providers/viz/VizMetadataMapper.kt#L109

**Comment by papaj-na-wrotkach** [comment]
Also, it would be a good idea to throw a specific exception if the path isn't modified by `String.removePrefix` and `String.removeSurrounding`

**Comment by shedman214** [comment]
@papaj-na-wrotkach  where would i make those changes as I use unraid
![image](https://github.com/user-attachments/assets/b0dac28f-adbb-45c5-9db5-e04cf5e1c85e)

**Comment by papaj-na-wrotkach** [comment]
The changes should be made by the developer, or one could create a pull request with those changes.

**Comment by shedman214** [comment]
@Snd-R any chance of making the changes for viz media

**Comment by papaj-na-wrotkach** [comment]
🎉

**Comment by shedman214** [comment]
any update?

**Comment by papaj-na-wrotkach** [comment]
Thanks to @Snd-R
