### ISSUE TITLE
Feature Request: Search w/o Brackets included in the search

### ISSUE THREAD

**Issue by loocool2** [Snd-R/komf#38]
I leave the ripper tags in the file folder names for each of my entries, so search fails a lot of the time. If a failed search can be retried without any words within brackets {}, [], () to be safe, it could improve the success rate of searches.

**Comment by LazyGeniusMan** [comment]
If this is implemented, would be nice if it's configurable, because `mangaupdates` use parentheses as identifier to series name (they don't have same series name). Below some random example of how mangaupdates differentiate series name with the same name but different author
![image](https://user-images.githubusercontent.com/58850480/215255105-a4e26d1b-2123-43b1-abe6-8c4ad51868e3.png)
