### ISSUE TITLE
Series not added to the Sqlite database

### ISSUE THREAD

**Issue by ItoshikiMonset** [Snd-R/komf#43]
Running Komf and Kavita latest version in docker, arch64, ubuntu 20.04.

Komf works perfectly with kavita, it adds metadata and works as intended, but I wasn't sure how it works for old series till I realized it must add the info in the db created in the config volume.

It doesn't seem to add metadata to series as they're added in Kavita, but the manual trigger with the userscript and command line works fine.
What buffles me the most is that series don't get added to the database, hence every time I run a new scan for metadata, it starts at 0. (It created the db file with the predefined template when I installed Komf, but nothing else get added to it)

Notifications for Discord also don't work; it worked once, but I'm not sure why it doesn't anymore (I think it must be database-related too).
Permissions are good too.
I tried looking at the logs for the problem, but it doesn't show anything weird; it shows connected, pings Kavita, receives metadata, and sends metadata to Kavita.
Only once did I see some incompatibility with arch64 when I reinstalled it (especially with the sources that were feathered at the beginning for sqlite and jar), but I can't see the logs for it anymore.
Could it be that the sources for compiling are not fully compartible with arch64? I'm not sure what other information I can provide, sadly.

**Comment by Snd-R** [comment]
It only adds series record to database on manual identification so that when you add new books it will pull metadata from source that you chose
Automatic identification will always launch new search, it's intended behavior.

Discord notifications and new series detection might not work properly if your kavita and komf containers don't have matching timezones
If you have `TZ=Your/Timezone` environment variable in kavita you should also added it to komf container

**Comment by ItoshikiMonset** [comment]
Thank you, I know understood how it works.
Also the timezone fixed the discord notifications! It now sends notifications when new books are added as intended. :)
Thank you again.
